<?php
declare(strict_types=1);
require_once __DIR__ . '/../vendor/autoload.php';
require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/performance_report.php';
require_once __DIR__ . '/../includes/report_generator.php';

// The Vite development UI runs on port 5173 while downloads are served by
// Apache on port 80. Allow that trusted local origin to send the PHP session
// cookie and read download headers.
$origin = (string) ($_SERVER['HTTP_ORIGIN'] ?? '');
if (preg_match('#^https?://(?:localhost|127\.0\.0\.1)(?::\d+)?$#i', $origin)) {
    header('Access-Control-Allow-Origin: ' . $origin);
    header('Access-Control-Allow-Credentials: true');
    header('Access-Control-Expose-Headers: Content-Disposition, Content-Type, Content-Length');
    header('Vary: Origin');
}
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'OPTIONS') {
    header('Access-Control-Allow-Methods: GET, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type, Accept');
    http_response_code(204);
    exit;
}

$user = current_user();
if (!$user || !in_array($user['role'] ?? '', ['admin_hr', 'vpaa', 'dean', 'program_head'], true)) { http_response_code(403); exit('Unauthorized'); }
$filters = [
    'report_type' => $_GET['report_type'] ?? 'department', 'department_id' => $_GET['department_id'] ?? 0,
    'role' => $_GET['role'] ?? 'teacher', 'program' => $_GET['program'] ?? '',
    'period_id' => $_GET['period_id'] ?? 0, 'sort' => $_GET['sort'] ?? 'name',
];
$metadata = performance_report_metadata();
try {
    [$filters] = performance_report_user_scope($user, $filters, $metadata);
} catch (PerformanceReportScopeException $error) {
    http_response_code(403);
    exit('Forbidden: ' . $error->getMessage());
}
$report = performance_report_build($filters);
$overall = $report['report_type'] === 'overall_department';
$includeDepartmentColumn = !$overall && $report['report_type'] !== 'department';
$headers = $overall
    ? ['Department', 'Personnel', 'Peer Mean', 'Head Mean', 'PH/SC Mean', 'Overall Mean', 'Level of Performance']
    : array_values(array_filter(['Name', $includeDepartmentColumn ? 'Department' : null, 'Program', 'Peer', 'Head', 'PH/SC', 'Total', 'Mean', 'Level of Performance']));
$value = static fn ($score): string => $score === null ? 'N/A' : number_format((float) $score, 2);
$rows = array_map(static function (array $row) use ($overall, $includeDepartmentColumn, $value): array {
    return $overall
        ? [$row['department'], $row['personnel'], $value($row['peer']), $value($row['head']), $value($row['phsc']), $value($row['mean']), $row['level']]
        : array_values(array_filter([$row['name'], $includeDepartmentColumn ? $row['department'] : null, $row['program'] ?: 'N/A', $value($row['peer']), $value($row['head']), $value($row['phsc']), $value($row['total']), $value($row['mean']), $row['level']], static fn ($item) => $item !== null));
}, $report['rows']);
$period = $report['period'];
$periodLabel = $period ? trim(($period['school_year'] ?: $period['period_name']) . ($period['semester'] ? ' / ' . $period['semester'] : '')) : 'All Evaluation Periods';
$title = $overall ? 'OVERALL DEPARTMENT PERFORMANCE REPORT' : 'PERFORMANCE FACTORS APPRAISAL';
$filenamePart = static function ($value): string {
    $value = trim((string) $value);
    $value = preg_replace('/[^A-Za-z0-9]+/', '-', $value) ?? '';
    return trim($value, '-') ?: 'Not-Specified';
};
$departmentFilename = $overall
    ? 'All-Departments'
    : $filenamePart($report['department_code'] ?: $report['department']);
$periodFilename = $filenamePart($periodLabel);
$scopeFilename = $overall
    ? 'Overall-Performance-Results'
    : $filenamePart($report['role_label'] . '-Performance-Results');
$downloadBaseName = 'APPRAISIA-' . $departmentFilename . '-' . $periodFilename . '-' . $scopeFilename;
$institutionLogo = (string) ($report['assets']['institution_logo']['path'] ?? '');
$departmentLogo = (string) ($report['assets']['department_logo']['path'] ?? '');
$format = $_GET['format'] ?? 'pdf';
$legendText = 'Legend: Excellent 4.50-5.00 | Very Satisfactory 3.75-4.49 | Satisfactory 3.00-3.74 | Needs Improvement below 3.00 | Incomplete/N/A = required results unavailable';
if ($format === 'excel') {
    $excelHeader = [
        'NOTRE DAME OF MIDSAYAP COLLEGE',
        $overall ? 'INSTITUTIONAL ACADEMIC DEPARTMENTS' : strtoupper((string) $report['department']),
        $title,
        $report['role_label'] . ' — ' . $periodLabel,
        'Program: ' . $report['program'] . '    |    Generated: ' . date('F j, Y') . '    |    Generated By: ' . ($user['full_name'] ?? 'Authorized User'),
        $legendText,
    ];
    (new ReportGenerator('Notre Dame of Midsayap College - ' . $title . ' - ' . $periodLabel, $title, $headers, $rows, $excelHeader))->exportExcel($downloadBaseName . '.xlsx');
}

$orientation = ($_GET['orientation'] ?? 'auto') === 'portrait' ? 'P' : 'L';
$mpdf = new \Mpdf\Mpdf(['mode' => 'utf-8', 'format' => 'A4-' . $orientation, 'margin_left' => 12, 'margin_right' => 12, 'margin_top' => 12, 'margin_bottom' => 16]);
$mpdf->showImageErrors = true;
$mpdf->SetHTMLFooter('<div style="font-size:8pt;color:#64748b;border-top:1px solid #cbd5e1;padding-top:5px">APPRAISIA Performance Factors Appraisal &nbsp; | &nbsp; Generated ' . date('F j, Y') . '<span style="float:right">Page {PAGENO} of {nbpg}</span></div>');
$html = '<style>body{font-family:Arial,sans-serif;color:#17231f;font-size:9pt}.report-head{page-break-inside:avoid}.head{text-align:center}.brand-table{width:100%;border:0;table-layout:fixed}.brand-table td{border:0;padding:0;vertical-align:middle}.brand-logo{width:15%;text-align:center}.brand-logo img{width:70px;height:70px}.brand-copy{width:70%;text-align:center}.head h1{font-family:Georgia,serif;font-size:17pt;margin:0}.head h2{font-size:12pt;margin:4px 0;text-transform:uppercase}.head p{margin:2px}.divider{border-top:2px solid #174f38;margin:10px 0 16px}.title{text-align:center;margin:0 0 15px}.title h3{font-size:14pt;margin:0 0 7px}.title-line{margin:3px 0;line-height:1.35}.title-role{font-weight:bold}.meta{width:100%;margin:10px 0 13px;border-collapse:separate;border-spacing:5px;page-break-inside:avoid}.meta td{width:33.33%;padding:8px 9px;border:1px solid #d8e3de;background:#f7faf8;vertical-align:top;line-height:1.35}.meta-label{color:#64748b;font-size:7pt;text-transform:uppercase}.meta-value{color:#17231f;font-size:8.5pt}table.report{width:100%;border-collapse:collapse;table-layout:fixed}table.report thead{display:table-header-group}table.report tr{page-break-inside:avoid}table.report th{background:#246b49;color:#fff;border:1px solid #174f38;padding:7px 4px;text-align:center;font-size:8pt}table.report td{border:1px solid #cbd5d0;padding:6px 5px;overflow-wrap:break-word}table.report tbody tr:nth-child(even){background:#f4f8f6}table.report td.num{text-align:center;font-variant-numeric:tabular-nums}.center{text-align:center}.legend{margin-top:9px;padding:7px 9px;border:1px solid #cbded3;background:#f5faf7;font-size:7.5pt;line-height:1.45;page-break-inside:avoid}.sign{margin-top:42px;width:48%;page-break-inside:avoid;text-align:center}.signature-space{height:22px}.signature-line{border-top:1px solid #17231f;padding-top:6px;line-height:1.4}.sign-name{font-size:9.5pt;font-weight:bold}.sign-detail{font-size:8.5pt;font-weight:normal}</style>';
$institutionLogoBinary = $institutionLogo !== '' && is_readable($institutionLogo) ? file_get_contents($institutionLogo) : false;
$departmentLogoBinary = $departmentLogo !== '' && is_readable($departmentLogo) ? file_get_contents($departmentLogo) : false;
// mPDF's native image registry is more reliable than filesystem URLs on
// Windows/Apache. Binary image data stays outside the HTML, avoiding both
// broken local paths and the PCRE limit caused by base64 data URIs.
if ($institutionLogoBinary !== false) $mpdf->imageVars['appraisaInstitutionLogo'] = $institutionLogoBinary;
if ($departmentLogoBinary !== false) $mpdf->imageVars['appraisaDepartmentLogo'] = $departmentLogoBinary;
$leftLogo = $institutionLogoBinary !== false
    ? '<img alt="NDMC seal" width="70" height="70" src="var:appraisaInstitutionLogo" style="object-fit:contain">'
    : '';
$rightLogo = $departmentLogoBinary !== false
    ? '<img alt="Department logo" width="70" height="70" src="var:appraisaDepartmentLogo" style="object-fit:contain">'
    : '';
$schoolYear = htmlspecialchars((string) ($period['school_year'] ?? $period['period_name'] ?? 'All Evaluation Periods'));
$semester = htmlspecialchars((string) ($period['semester'] ?? ''));
$html .= '<div class="report-head"><div class="head"><table class="brand-table"><tr><td class="brand-logo">' . $leftLogo . '</td><td class="brand-copy"><h1>Notre Dame of Midsayap College</h1><h2>' . htmlspecialchars($overall ? 'Institutional Academic Departments' : $report['department']) . '</h2><p>Midsayap, Cotabato</p></td><td class="brand-logo">' . $rightLogo . '</td></tr></table></div><div class="divider"></div>';
$html .= '<div class="title"><h3>' . $title . '</h3><div class="title-line title-role">' . htmlspecialchars($report['role_label']) . '</div><div class="title-line">SY ' . $schoolYear . '</div>' . ($semester !== '' ? '<div class="title-line">' . $semester . '</div>' : '') . '</div></div>';
$metadataItems = [['Department', $report['department']], ['Program', $report['program']], ['Role', $report['role_label']], ['Evaluation Period', $periodLabel], ['Generated', date('F j, Y')], ['Generated By', $user['full_name'] ?? 'Authorized User']];
$html .= '<table class="meta"><tr>'; foreach ($metadataItems as $index => $item) { if ($index === 3) $html .= '</tr><tr>'; $html .= '<td><span class="meta-label">' . htmlspecialchars((string) $item[0]) . '</span><br><strong class="meta-value">' . htmlspecialchars((string) $item[1]) . '</strong></td>'; } $html .= '</tr></table>';
$html .= '<table class="report"><thead><tr>'; foreach ($headers as $header) $html .= '<th>' . htmlspecialchars($header) . '</th>'; $html .= '</tr></thead><tbody>';
foreach ($rows as $row) { $html .= '<tr>'; foreach ($row as $index => $cell) $html .= '<td class="' . ($index > 2 && $index < count($row)-1 ? 'num' : '') . '">' . htmlspecialchars((string) $cell) . '</td>'; $html .= '</tr>'; }
if ($rows === []) $html .= '<tr><td colspan="' . count($headers) . '" class="center">No completed evaluation results found for the selected filters.</td></tr>';
$html .= '</tbody></table>';
$html .= '<div class="legend"><strong>' . htmlspecialchars($legendText) . '</strong><br>Peer = peer evaluators; Head = Dean or Program Head; PH/SC = Program Head / Section Chair; Mean = overall computed rating.</div>';
if (!$overall) $html .= '<div class="sign"><div class="signature-space"></div><div class="signature-line"><span class="sign-name">' . htmlspecialchars($report['signatory'] ?: 'Dean assignment not configured') . '</span><br><span class="sign-detail">Dean</span><br><span class="sign-detail">' . htmlspecialchars($report['department']) . '</span></div></div>';
if ($format === 'word') {
    $filename = $downloadBaseName . '.docx';
    $wordImageExtension = static fn (string $mime): string => match ($mime) {
        'image/jpeg' => 'jpg', 'image/gif' => 'gif', 'image/webp' => 'webp', default => 'png',
    };
    $institutionImageName = 'institution-logo.' . $wordImageExtension((string) ($report['assets']['institution_logo']['mime'] ?? 'image/png'));
    $departmentImageName = 'department-logo.' . $wordImageExtension((string) ($report['assets']['department_logo']['mime'] ?? 'image/png'));
    $xml = static fn ($text): string => htmlspecialchars((string) $text, ENT_XML1 | ENT_QUOTES, 'UTF-8');
    $run = static fn ($text, bool $bold = false, int $size = 20, string $color = ''): string => '<w:r><w:rPr>' . ($bold ? '<w:b/>' : '') . ($color !== '' ? '<w:color w:val="' . $color . '"/>' : '') . '<w:sz w:val="' . $size . '"/><w:szCs w:val="' . $size . '"/></w:rPr><w:t xml:space="preserve">' . htmlspecialchars((string) $text, ENT_XML1 | ENT_QUOTES, 'UTF-8') . '</w:t></w:r>';
    $paragraph = static function ($text, bool $bold = false, int $size = 20, string $align = 'left', string $color = '') use ($run): string {
        return '<w:p><w:pPr><w:jc w:val="' . $align . '"/><w:spacing w:after="80"/></w:pPr>' . $run($text, $bold, $size, $color) . '</w:p>';
    };
    $drawing = static function (string $relationId, int $id, string $name): string {
        return '<w:p><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="720000" cy="720000"/><wp:docPr id="' . $id . '" name="' . htmlspecialchars($name, ENT_XML1 | ENT_QUOTES, 'UTF-8') . '"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="' . $id . '" name="' . htmlspecialchars($name, ENT_XML1 | ENT_QUOTES, 'UTF-8') . '"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="' . $relationId . '"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="720000" cy="720000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>';
    };
    $leftImage = $institutionLogo !== '' && is_file($institutionLogo) ? $drawing('rId1', 1, 'NDMC Seal') : $paragraph('', false, 10, 'center');
    $rightImage = $departmentLogo !== '' && is_file($departmentLogo) ? $drawing('rId2', 2, 'Department Logo') : $paragraph('', false, 10, 'center');
    $brand = '<w:tbl><w:tblPr><w:tblW w:w="5000" w:type="pct"/><w:tblLayout w:type="fixed"/><w:tblBorders><w:top w:val="nil"/><w:left w:val="nil"/><w:bottom w:val="nil"/><w:right w:val="nil"/><w:insideH w:val="nil"/><w:insideV w:val="nil"/></w:tblBorders></w:tblPr><w:tblGrid><w:gridCol w:w="1800"/><w:gridCol w:w="10800"/><w:gridCol w:w="1800"/></w:tblGrid><w:tr><w:tc><w:tcPr><w:tcW w:w="1800" w:type="dxa"/><w:vAlign w:val="center"/></w:tcPr>' . $leftImage . '</w:tc><w:tc><w:tcPr><w:tcW w:w="10800" w:type="dxa"/><w:vAlign w:val="center"/></w:tcPr>' . $paragraph('Notre Dame of Midsayap College', true, 30, 'center') . $paragraph($overall ? 'INSTITUTIONAL ACADEMIC DEPARTMENTS' : strtoupper((string) $report['department']), true, 23, 'center') . $paragraph('Midsayap, Cotabato', false, 20, 'center') . '</w:tc><w:tc><w:tcPr><w:tcW w:w="1800" w:type="dxa"/><w:vAlign w:val="center"/></w:tcPr>' . $rightImage . '</w:tc></w:tr></w:tbl>';
    $wordMetaItems = [['Department', $report['department']], ['Program', $report['program']], ['Role', $report['role_label']], ['Evaluation Period', $periodLabel], ['Generated', date('F j, Y')], ['Generated By', $user['full_name'] ?? 'Authorized User']];
    $metadataTable = '<w:tbl><w:tblPr><w:tblW w:w="5000" w:type="pct"/><w:tblLayout w:type="fixed"/><w:tblBorders><w:top w:val="single" w:sz="4" w:color="D8E3DE"/><w:left w:val="single" w:sz="4" w:color="D8E3DE"/><w:bottom w:val="single" w:sz="4" w:color="D8E3DE"/><w:right w:val="single" w:sz="4" w:color="D8E3DE"/><w:insideH w:val="single" w:sz="4" w:color="D8E3DE"/><w:insideV w:val="single" w:sz="4" w:color="D8E3DE"/></w:tblBorders><w:tblCellMar><w:top w:w="100" w:type="dxa"/><w:left w:w="120" w:type="dxa"/><w:bottom w:w="100" w:type="dxa"/><w:right w:w="120" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid><w:gridCol w:w="4800"/><w:gridCol w:w="4800"/><w:gridCol w:w="4800"/></w:tblGrid>';
    foreach ($wordMetaItems as $index => $item) {
        if ($index % 3 === 0) $metadataTable .= '<w:tr>';
        $metadataTable .= '<w:tc><w:tcPr><w:tcW w:w="4800" w:type="dxa"/><w:shd w:fill="F5F9F7"/></w:tcPr>' . $paragraph(strtoupper((string) $item[0]), true, 13, 'left', '64748B') . $paragraph($item[1], true, 16, 'left', '17231F') . '</w:tc>';
        if ($index % 3 === 2) $metadataTable .= '</w:tr>';
    }
    $metadataTable .= '</w:tbl>';
    $columnWidths = $overall ? [4000,1300,1500,1500,1500,1500,3100] : ($includeDepartmentColumn ? [2400,2200,1300,1000,1000,1000,1000,1000,3500] : [3000,1400,1100,1100,1100,1100,1100,3500]);
    $table = '<w:tbl><w:tblPr><w:tblW w:w="5000" w:type="pct"/><w:tblLayout w:type="fixed"/><w:tblBorders><w:top w:val="single" w:sz="5" w:color="174F38"/><w:left w:val="single" w:sz="5" w:color="174F38"/><w:bottom w:val="single" w:sz="5" w:color="174F38"/><w:right w:val="single" w:sz="5" w:color="174F38"/><w:insideH w:val="single" w:sz="4" w:color="CBD5E1"/><w:insideV w:val="single" w:sz="4" w:color="CBD5E1"/></w:tblBorders><w:tblCellMar><w:top w:w="90" w:type="dxa"/><w:left w:w="90" w:type="dxa"/><w:bottom w:w="90" w:type="dxa"/><w:right w:w="90" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid>';
    foreach ($columnWidths as $width) $table .= '<w:gridCol w:w="' . $width . '"/>';
    $table .= '</w:tblGrid><w:tr><w:trPr><w:tblHeader/></w:trPr>';
    foreach ($headers as $index => $header) $table .= '<w:tc><w:tcPr><w:tcW w:w="' . ($columnWidths[$index] ?? 1200) . '" w:type="dxa"/><w:shd w:fill="246B49"/><w:vAlign w:val="center"/></w:tcPr>' . $paragraph($header, true, 16, 'center', 'FFFFFF') . '</w:tc>';
    $table .= '</w:tr>';
    foreach ($rows as $row) {
        $table .= '<w:tr>';
        foreach ($row as $index => $cell) $table .= '<w:tc><w:tcPr><w:tcW w:w="' . ($columnWidths[$index] ?? 1200) . '" w:type="dxa"/><w:vAlign w:val="center"/></w:tcPr>' . $paragraph($cell, false, 16, $index === 0 ? 'left' : 'center') . '</w:tc>';
        $table .= '</w:tr>';
    }
    if ($rows === []) $table .= '<w:tr><w:tc><w:tcPr><w:gridSpan w:val="' . count($headers) . '"/></w:tcPr>' . $paragraph('No completed evaluation results found for the selected filters.', false, 18, 'center') . '</w:tc></w:tr>';
    $table .= '</w:tbl>';
    $body = $brand . '<w:p><w:pPr><w:pBdr><w:bottom w:val="single" w:sz="16" w:color="174F38"/></w:pBdr><w:spacing w:after="160"/></w:pPr></w:p>'
        . $paragraph($title, true, 26, 'center') . $paragraph($report['role_label'], true, 20, 'center') . $paragraph($periodLabel, false, 20, 'center')
        . $paragraph('', false, 8) . $metadataTable . $paragraph('', false, 8) . $table . $paragraph($legendText, true, 14, 'left', '174F38') . $paragraph('Peer = peer evaluators; Head = Dean or Program Head; PH/SC = Program Head / Section Chair; Mean = overall computed rating.', false, 13, 'left', '64748B');
    if (!$overall) $body .= $paragraph('', false, 18) . $paragraph('', false, 18) . '<w:tbl><w:tblPr><w:tblW w:w="5600" w:type="dxa"/><w:jc w:val="left"/></w:tblPr><w:tblGrid><w:gridCol w:w="5600"/></w:tblGrid><w:tr><w:tc><w:tcPr><w:tcBorders><w:top w:val="single" w:sz="6" w:color="17231F"/></w:tcBorders></w:tcPr>' . $paragraph($report['signatory'] ?: 'Dean assignment not available', true, 18, 'center') . $paragraph('Dean', false, 16, 'center') . $paragraph($report['department'], false, 15, 'center') . '</w:tc></w:tr></w:tbl>';
    $document = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><w:body>' . $body . '<w:sectPr><w:pgSz w:w="15840" w:h="12240" w:orient="landscape"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720"/></w:sectPr></w:body></w:document>';
    $relationships = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">';
    if ($institutionLogo !== '' && is_file($institutionLogo)) $relationships .= '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/' . $institutionImageName . '"/>';
    if ($departmentLogo !== '' && is_file($departmentLogo)) $relationships .= '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/' . $departmentImageName . '"/>';
    $relationships .= '</Relationships>';
    $types = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Default Extension="jpg" ContentType="image/jpeg"/><Default Extension="gif" ContentType="image/gif"/><Default Extension="webp" ContentType="image/webp"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>';
    $packageRels = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>';
    // The DOCX parts are assembled from single-quoted PHP fragments. Normalize any
    // defensive escaped quotes before packaging so Word receives valid OOXML.
    $document = str_replace('\\"', '"', $document);
    $relationships = str_replace('\\"', '"', $relationships);
    $types = str_replace('\\"', '"', $types);
    $packageRels = str_replace('\\"', '"', $packageRels);
    $tempFile = tempnam(sys_get_temp_dir(), 'appraisa-docx-');
    $zip = new ZipArchive();
    if ($tempFile === false || $zip->open($tempFile, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) { http_response_code(500); exit('Unable to create Word report.'); }
    $zip->addFromString('[Content_Types].xml', $types);
    $zip->addFromString('_rels/.rels', $packageRels);
    $zip->addFromString('word/document.xml', $document);
    $zip->addFromString('word/_rels/document.xml.rels', $relationships);
    if ($institutionLogo !== '' && is_file($institutionLogo)) $zip->addFile($institutionLogo, 'word/media/' . $institutionImageName);
    if ($departmentLogo !== '' && is_file($departmentLogo)) $zip->addFile($departmentLogo, 'word/media/' . $departmentImageName);
    $zip->close();
    header('Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Content-Length: ' . filesize($tempFile));
    header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
    readfile($tempFile);
    unlink($tempFile);
    exit;
}
try {
    $mpdf->WriteHTML($html);
    $pdfFile = tempnam(sys_get_temp_dir(), 'appraisa-pdf-');
    if ($pdfFile === false) throw new RuntimeException('Unable to create a temporary PDF file.');
    $mpdf->Output($pdfFile, \Mpdf\Output\Destination::FILE);
    $pdfSize = filesize($pdfFile);
    if ($pdfSize === false || $pdfSize < 100) {
        @unlink($pdfFile);
        throw new RuntimeException('The generated PDF file is empty.');
    }
    while (ob_get_level() > 0) ob_end_clean();
    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="' . $downloadBaseName . '.pdf"');
    header('Content-Length: ' . $pdfSize);
    header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
    header('X-Content-Type-Options: nosniff');
    readfile($pdfFile);
    @unlink($pdfFile);
    exit;
} catch (Throwable $error) {
    error_log('APPRAISIA performance PDF export failed: ' . $error->getMessage());
    if (!headers_sent()) http_response_code(500);
    exit('Unable to generate the PDF report. Please try again.');
}
