<?php
declare(strict_types=1);
ob_start();

require_once __DIR__ . '/../vendor/autoload.php';
require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/db.php';
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/report_generator.php';
require_once __DIR__ . '/../includes/subject_assignments.php';

$origin = (string) ($_SERVER['HTTP_ORIGIN'] ?? '');
if (preg_match('#^https?://(?:localhost|127\.0\.0\.1)(?::\d+)?$#i', $origin)) {
    header('Access-Control-Allow-Origin: ' . $origin);
    header('Access-Control-Allow-Credentials: true');
    header('Access-Control-Expose-Headers: Content-Disposition, Content-Type, Content-Length');
    header('Vary: Origin');
}
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'OPTIONS') {
    header('Access-Control-Allow-Methods: GET, OPTIONS');
    http_response_code(204);
    exit;
}

$user = current_user();
if (!$user || ($user['role'] ?? '') !== 'admin_hr') {
    http_response_code(403);
    exit('Forbidden: Admin/HR access is required.');
}

$department = trim((string) ($_GET['department'] ?? ''));
$format = strtolower(trim((string) ($_GET['format'] ?? 'pdf')));
if (!in_array($format, ['excel', 'word', 'pdf'], true)) {
    http_response_code(400);
    exit('Unsupported export format.');
}

// Password and password-hash columns are intentionally never selected.
$db = db();
subject_assignments_ensure_schema();
$sql = "SELECT u.full_name, u.department, u.role, u.user_code, u.must_change_password,
               COALESCE(NULLIF(u.program,''), GROUP_CONCAT(DISTINCT CONCAT(sa.subject_code,IF(fsa.is_primary=1,' (Primary)','')) ORDER BY fsa.is_primary DESC,sa.subject_name SEPARATOR ', '), 'Unassigned') assignment
        FROM users u
        LEFT JOIN faculty f ON f.user_id=u.id
        LEFT JOIN faculty_subject_assignments fsa ON fsa.faculty_id=f.id
        LEFT JOIN subject_areas sa ON sa.id=fsa.subject_area_id
        WHERE u.role IN ('dean', 'program_head', 'teacher')";
$params = [];
if ($department !== '') {
    $sql .= " AND (
        u.department = ?
        OR u.department = (SELECT department_code FROM departments WHERE department_name = ? OR department_code = ? LIMIT 1)
        OR u.department = (SELECT department_name FROM departments WHERE department_name = ? OR department_code = ? LIMIT 1)
    )";
    $params = [$department, $department, $department, $department, $department];
}
$sql .= " GROUP BY u.id ORDER BY FIELD(u.role, 'dean', 'program_head', 'teacher'), u.full_name ASC";
$statement = $db->prepare($sql);
$statement->execute($params);
$records = $statement->fetchAll(PDO::FETCH_ASSOC);

$roleLabel = static fn (string $role): string => match ($role) {
    'admin_hr' => 'HRDM Director/Admin',
    'vpaa' => 'VPAA',
    'dean' => 'Dean',
    'program_head' => 'Program Head',
    'teacher' => 'Faculty Member',
    default => ucwords(str_replace('_', ' ', $role)),
};
$rows = array_map(static fn (array $record): array => [
    (string) $record['full_name'],
    (string) $record['user_code'],
    'APPRAISIA_NDMC',
    $roleLabel((string) $record['role']),
    (string) $record['assignment'],
], $records);

$headers = ['Full Name', 'Username', 'Temporary Password', 'Role', 'Program / Primary Subject'];
$scope = $department !== '' ? $department : 'All Departments';
$date = date('Y-m-d');
$safeScope = trim((string) preg_replace('/[^A-Za-z0-9]+/', '-', $scope), '-') ?: 'All-Departments';
$baseName = "APPRAISIA-User-Account-Report-{$safeScope}-{$date}";
$documentHeader = [
    'NOTRE DAME OF MIDSAYAP COLLEGE',
    'APPRAISIA USER ACCOUNT REPORT',
    'Department: ' . $scope,
    'Generated: ' . date('F j, Y g:i A') . ' | Generated By: ' . ($user['full_name'] ?? 'System Administrator'),
    'Security Notice: Existing user-created passwords are never included. APPRAISIA_NDMC is the institution standard temporary password.',
];

$generator = new ReportGenerator('APPRAISIA User Account Report — ' . $scope, 'User Account Report', $headers, $rows, $documentHeader);
if ($format === 'excel') {
    $generator->exportExcel($baseName . '.xlsx');
}
if ($format === 'pdf') {
    $generator->exportPdf($baseName . '.pdf');
}

$xml = static fn ($value): string => htmlspecialchars((string) $value, ENT_XML1 | ENT_QUOTES, 'UTF-8');
$paragraph = static function ($text, bool $bold = false, int $size = 20, string $alignment = 'left', string $color = '17231F') use ($xml): string {
    return '<w:p><w:pPr><w:jc w:val="' . $alignment . '"/></w:pPr><w:r><w:rPr>'
        . ($bold ? '<w:b/>' : '') . '<w:sz w:val="' . $size . '"/><w:color w:val="' . $color . '"/></w:rPr>'
        . '<w:t xml:space="preserve">' . $xml($text) . '</w:t></w:r></w:p>';
};
$widths = [3900, 2000, 2800, 2300, 3800];
$table = '<w:tbl><w:tblPr><w:tblW w:w="5000" w:type="pct"/><w:tblLayout w:type="fixed"/><w:tblBorders><w:top w:val="single" w:sz="5" w:color="2563EB"/><w:left w:val="single" w:sz="5" w:color="2563EB"/><w:bottom w:val="single" w:sz="5" w:color="2563EB"/><w:right w:val="single" w:sz="5" w:color="2563EB"/><w:insideH w:val="single" w:sz="4" w:color="CBD5E1"/><w:insideV w:val="single" w:sz="4" w:color="CBD5E1"/></w:tblBorders></w:tblPr><w:tblGrid>';
foreach ($widths as $width) $table .= '<w:gridCol w:w="' . $width . '"/>';
$table .= '</w:tblGrid><w:tr><w:trPr><w:tblHeader/></w:trPr>';
foreach ($headers as $index => $header) {
    $table .= '<w:tc><w:tcPr><w:tcW w:w="' . $widths[$index] . '" w:type="dxa"/><w:shd w:fill="2563EB"/></w:tcPr>' . $paragraph($header, true, 18, 'center', 'FFFFFF') . '</w:tc>';
}
$table .= '</w:tr>';
foreach ($rows as $row) {
    $table .= '<w:tr>';
    foreach ($row as $index => $cell) {
        $table .= '<w:tc><w:tcPr><w:tcW w:w="' . $widths[$index] . '" w:type="dxa"/></w:tcPr>' . $paragraph($cell, false, 18, $index === 0 ? 'left' : 'center') . '</w:tc>';
    }
    $table .= '</w:tr>';
}
if ($rows === []) {
    $table .= '<w:tr><w:tc><w:tcPr><w:gridSpan w:val="5"/></w:tcPr>' . $paragraph('No Dean, Program Head, or Faculty accounts found for this department.', false, 18, 'center') . '</w:tc></w:tr>';
}
$table .= '</w:tbl>';
$body = $paragraph('Notre Dame of Midsayap College', true, 32, 'center')
    . $paragraph('APPRAISIA USER ACCOUNT REPORT', true, 25, 'center')
    . $paragraph('Department: ' . $scope, false, 20, 'center', '475569')
    . $paragraph('Generated: ' . date('F j, Y g:i A'), false, 18, 'center', '64748B')
    . $paragraph('', false, 8) . $table . $paragraph('', false, 8)
    . $paragraph('Security Notice: Existing user-created passwords are never displayed or exported. APPRAISIA_NDMC is the institution standard temporary password.', false, 16, 'left', '475569');
$document = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>' . $body . '<w:sectPr><w:pgSz w:w="15840" w:h="12240" w:orient="landscape"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720"/></w:sectPr></w:body></w:document>';
$types = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>';
$relationships = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>';
$document = str_replace('\"', '"', $document);
$types = str_replace('\"', '"', $types);
$relationships = str_replace('\"', '"', $relationships);
$tempFile = tempnam(sys_get_temp_dir(), 'appraisa-user-docx-');
$zip = new ZipArchive();
if ($tempFile === false || $zip->open($tempFile, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
    http_response_code(500);
    exit('Unable to create Word report.');
}
$zip->addFromString('[Content_Types].xml', $types);
$zip->addFromString('_rels/.rels', $relationships);
$zip->addFromString('word/document.xml', $document);
$zip->close();
$size = filesize($tempFile);
while (ob_get_level() > 0) ob_end_clean();
header('Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document');
header('Content-Disposition: attachment; filename="' . $baseName . '.docx"');
header('Content-Length: ' . $size);
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
readfile($tempFile);
unlink($tempFile);
exit;
