<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/config.php';require_once __DIR__.'/../includes/db.php';require_once __DIR__.'/../includes/admin_data.php';
$apply=in_array('--apply',$argv,true);$db=db();$periods=admin_all("SELECT id,period_name FROM appraisal_periods WHERE period_name IN('2024 APPRAISAL PERIOD','2025 APPRAISAL PERIOD','2026 ACADEMIC YEAR') ORDER BY id");
$dean=admin_one("SELECT u.id,u.full_name FROM departments d JOIN users u ON u.id=d.dean_user_id WHERE d.department_name='College of Information Technology and Engineering'");$vpaa=admin_one("SELECT id,full_name FROM users WHERE role='vpaa' AND is_active=1 ORDER BY id LIMIT 1");
if(!$dean||!$vpaa)throw new RuntimeException('The active CITE Dean or VPAA account was not found.');
$records=admin_all("SELECT se.*,u.full_name,epp.role_snapshot period_role,epp.program_id,epp.department_id,ap.id period_id FROM pmas_self_evaluations se JOIN users u ON u.id=se.user_id JOIN appraisal_periods ap ON ap.period_name=se.evaluation_period JOIN evaluation_period_participation epp ON epp.evaluation_period_id=ap.id AND epp.user_id=se.user_id WHERE ap.period_name IN('2024 APPRAISAL PERIOD','2025 APPRAISAL PERIOD','2026 ACADEMIC YEAR') AND epp.department_snapshot='College of Information Technology and Engineering' AND se.status='submitted'");
$summary=['mode'=>$apply?'apply':'dry-run','records'=>count($records),'dean'=>$dean['full_name'],'vpaa'=>$vpaa['full_name']];if(!$apply){echo json_encode($summary,JSON_PRETTY_PRINT),PHP_EOL;exit;}
$dir=__DIR__.'/../private-backups';if(!is_dir($dir)&&!mkdir($dir,0770,true)&&!is_dir($dir))throw new RuntimeException('Cannot create backup directory.');$path=$dir.'/cite-self-review-approvals-'.date('Ymd-His').'.json';file_put_contents($path,json_encode(['created_at'=>date(DATE_ATOM),'records'=>$records],JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR));
$actor=(int)(admin_one("SELECT id FROM users WHERE role='admin_hr' AND is_active=1 ORDER BY id LIMIT 1")['id']??0);$counts=['program_head'=>0,'dean'=>0,'vpaa'=>0];$db->beginTransaction();try{
 foreach($records as $r){$role=(string)$r['period_role'];$id=(int)$r['id'];$notes='SAMPLE REVIEW: Completed record verified and approved for the selected evaluation period.';
  if($role==='teacher'){$head=admin_one("SELECT eph.user_id,u.full_name FROM evaluation_period_program_heads eph JOIN users u ON u.id=eph.user_id WHERE eph.evaluation_period_id=? AND eph.program_id=? ORDER BY eph.is_primary DESC,eph.id LIMIT 1",[(int)$r['period_id'],(int)$r['program_id']]);if(!$head)$head=admin_one("SELECT p.program_head_user_id user_id,u.full_name FROM programs p JOIN users u ON u.id=p.program_head_user_id WHERE p.id=? AND p.is_active=1",[(int)$r['program_id']]);if($head){$db->prepare("UPDATE pmas_self_evaluations SET program_head_review_status='approved',program_head_reviewed_by=?,program_head_reviewed_at=NOW(),program_head_review_notes=? WHERE id=?")->execute([(int)$head['user_id'],$notes,$id]);$db->prepare("INSERT INTO pmas_self_evaluation_audit_logs(self_evaluation_id,user_id,user_role,action_type,old_value,new_value,remarks) VALUES(?,?,'program_head','approved','Pending Program Head Review','Approved by Program Head',?)")->execute([$id,(int)$head['user_id'],$notes]);$counts['program_head']++;}
   $db->prepare("UPDATE pmas_self_evaluations SET dean_review_status='approved',dean_reviewed_by=?,dean_reviewed_at=NOW(),dean_review_notes=?,final_admin_submission_status='ready_for_admin',admin_review_status='pending' WHERE id=?")->execute([(int)$dean['id'],$notes,$id]);$counts['dean']++;
  }elseif($role==='program_head'){$db->prepare("UPDATE pmas_self_evaluations SET dean_review_status='approved',dean_reviewed_by=?,dean_reviewed_at=NOW(),dean_review_notes=?,final_admin_submission_status='ready_for_admin',admin_review_status='pending' WHERE id=?")->execute([(int)$dean['id'],$notes,$id]);$counts['dean']++;
  }elseif($role==='dean'){$db->prepare("UPDATE pmas_self_evaluations SET vpaa_review_status='approved',vpaa_reviewed_by=?,vpaa_reviewed_at=NOW(),vpaa_review_notes=? WHERE id=?")->execute([(int)$vpaa['id'],$notes,$id]);$db->prepare("INSERT INTO pmas_self_evaluation_audit_logs(self_evaluation_id,user_id,user_role,action_type,old_value,new_value,remarks) VALUES(?,?,'vpaa','approved','Pending VPAA Review','Approved by VPAA',?)")->execute([$id,(int)$vpaa['id'],$notes]);$counts['vpaa']++;continue;}else continue;
  $db->prepare("INSERT INTO pmas_self_evaluation_audit_logs(self_evaluation_id,user_id,user_role,action_type,old_value,new_value,remarks) VALUES(?,?,'dean','approved','Pending Dean Review','Approved by Dean',?)")->execute([$id,(int)$dean['id'],$notes]);
 }
 $db->prepare('INSERT INTO activity_logs(user_id,description) VALUES(?,?)')->execute([$actor,'Applied sample Program Head, Dean, and VPAA approvals to completed CITE self-evaluations for 2024-2026.']);$db->commit();
}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
$summary['backup']=$path;$summary['approvals']=$counts;echo json_encode($summary,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),PHP_EOL;
